# SPDX-FileCopyrightText: 2026 Sebastien Rousseau <sebastian.rousseau@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR MIT

disabled_rules:
  - trailing_whitespace
opt_in_rules:
  - empty_count
  - force_unwrapping
  - closure_spacing
  - fatal_error_message
line_length:
  warning: 120
  error: 160
type_body_length:
  warning: 300
  error: 400
